datasource:
  # Задаём базу данных, к которой будет происходить подключение
  db:
    # Имя пользователя и пароль
    username: ""
    password: ""
    # Драйвер базы данных и URL
    # Используем embedded вариант базы H2
    # БД располагается в файле в текущей директории
    url: "jdbc:h2:./hexlet"
    ebean:
      migration:
        run: true